package com.ioc

import com.ioc.IProcessor.Companion.filer
import com.squareup.javapoet.JavaFile
import com.squareup.javapoet.TypeSpec

fun TypeSpec.writeClass(`package`: String) {
    val iocVersion = "1.1.9"
    val javaFile = JavaFile.builder(`package`, this).addFileComment("This file was generated by Ioc $iocVersion. Do not modify!").build()
    javaFile.writeTo(filer)
}